import type { RailheadVariantCatalog } from './types'

/**
 * Full railhead catalogue from client Numbers/CSV
 * (`docs/frontend/foto-intake/railheads-catalog.json`) + cropped product photos
 * (`apps/web/public/2d-masters/railheads/photos`).
 *
 * Status stays `provisional` until Marius signs live listino.
 * Prices are EX VAT. Missing prices stay 0 + provisional note.
 * Generated 2026-08-12 — do not hand-edit; regenerate from JSON.
 */
export const DEFAULT_RAILHEAD_VARIANT_CATALOG: RailheadVariantCatalog = {
  status: 'provisional',
  blockedReason: '',
  owner: 'Marius',
  entries: [
    {
      slug: "RH1",
      label: "RH1",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 1.3,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 184\u00d789\u00d720 mm \u00b7 \u00a31.3 ex VAT. Photo: /2d-masters/railheads/photos/RH1.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH10",
      label: "RH10",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.8,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 125\u00d748\u00d725 mm \u00b7 \u00a30.8 ex VAT. Photo: /2d-masters/railheads/photos/RH10.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH100",
      label: "RH100",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.6,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 160\u00d770\u00d728 mm \u00b7 \u00a30.6 ex VAT. Photo: /2d-masters/railheads/photos/RH100.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH102A",
      label: "RH102A",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.9,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 140\u00d770\u00d726 mm \u00b7 \u00a30.9 ex VAT. Photo: /2d-masters/railheads/photos/RH102A.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH108",
      label: "RH108",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.55,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 110\u00d765\u00d720 mm \u00b7 \u00a30.55 ex VAT. Photo: /2d-masters/railheads/photos/RH108.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH109",
      label: "RH109",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.95,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 160\u00d762\u00d716 mm \u00b7 \u00a30.95 ex VAT. Photo: /2d-masters/railheads/photos/RH109.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH110",
      label: "RH110",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 2,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 250\u00d7102\u00d725 mm \u00b7 \u00a32.0 ex VAT. Photo: /2d-masters/railheads/photos/RH110.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH111",
      label: "RH111",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.75,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 115\u00d730\u00d725 mm \u00b7 \u00a30.75 ex VAT. Photo: /2d-masters/railheads/photos/RH111.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH112",
      label: "RH112",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.85,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 124\u00d774\u00d716 mm \u00b7 \u00a30.85 ex VAT. Photo: /2d-masters/railheads/photos/RH112.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH113",
      label: "RH113",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 1.3,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 165\u00d785\u00d718 mm \u00b7 \u00a31.3 ex VAT. Photo: /2d-masters/railheads/photos/RH113.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH114",
      label: "RH114",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.8,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 140\u00d765\u00d716 mm \u00b7 \u00a30.8 ex VAT. Photo: /2d-masters/railheads/photos/RH114.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH122",
      label: "RH122",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 160\u00d765\u00d716 mm \u00b7 price TBD. Photo: /2d-masters/railheads/photos/RH122.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH124",
      label: "RH124",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 2.95,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 205\u00d760\u00d720 mm \u00b7 \u00a32.95 ex VAT. Photo: /2d-masters/railheads/photos/RH124.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH125",
      label: "RH125",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 1.7,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 170\u00d760\u00d720 mm \u00b7 \u00a31.7 ex VAT. Photo: /2d-masters/railheads/photos/RH125.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH126",
      label: "RH126",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.99,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 130\u00d725\u00d720 mm \u00b7 \u00a30.99 ex VAT. Photo: /2d-masters/railheads/photos/RH126.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH128",
      label: "RH128",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 1.3,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 180\u00d765\u00d720 mm \u00b7 \u00a31.3 ex VAT. Photo: /2d-masters/railheads/photos/RH128.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH13",
      label: "RH13",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.99,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 125\u00d740\u00d718 mm \u00b7 \u00a30.99 ex VAT. Photo: /2d-masters/railheads/photos/RH13.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH130",
      label: "RH130",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.75,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 100\u00d744\u00d712 mm \u00b7 \u00a30.75 ex VAT. Photo: /2d-masters/railheads/photos/RH130.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH14",
      label: "RH14",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.5,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 95\u00d725\u00d712 mm \u00b7 \u00a30.5 ex VAT. Photo: /2d-masters/railheads/photos/RH14.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH149",
      label: "RH149",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.45,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 130\u00d760\u00d712 mm \u00b7 \u00a30.45 ex VAT. Photo: /2d-masters/railheads/photos/RH149.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH151",
      label: "RH151",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 1.8,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 162\u00d736\u00d722 mm \u00b7 \u00a31.8 ex VAT. Photo: /2d-masters/railheads/photos/RH151.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH157",
      label: "RH157",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.65,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 130 mm \u00b7 \u00a30.65 ex VAT. Photo: /2d-masters/railheads/photos/RH157.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH159",
      label: "RH159",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 1.05,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 130 mm \u00b7 \u00a31.05 ex VAT. Photo: /2d-masters/railheads/photos/RH159.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH15WO",
      label: "RH15WO",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.45,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 124\u00d726\u00d718 mm \u00b7 \u00a30.45 ex VAT. Photo: /2d-masters/railheads/photos/RH15WO.webp (alias of RH15W)",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH16",
      label: "RH16",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 1.6,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 157\u00d738\u00d730 mm \u00b7 \u00a31.6 ex VAT. Photo: /2d-masters/railheads/photos/RH16.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH160",
      label: "RH160",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 1.6,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 160 mm \u00b7 \u00a31.6 ex VAT. Photo: /2d-masters/railheads/photos/RH160.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH17",
      label: "RH17",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 1.5,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 188\u00d750\u00d740 mm \u00b7 \u00a31.5 ex VAT. Photo: /2d-masters/railheads/photos/RH17.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH18",
      label: "RH18",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.35,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 80\u00d746\u00d720 mm \u00b7 \u00a30.35 ex VAT. Photo: /2d-masters/railheads/photos/RH18.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH19",
      label: "RH19",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.55,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 120\u00d765\u00d725 mm \u00b7 \u00a30.55 ex VAT. Photo: /2d-masters/railheads/photos/RH19.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH2",
      label: "RH2",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.5,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 150\u00d770\u00d716 mm \u00b7 \u00a30.5 ex VAT. Photo: /2d-masters/railheads/photos/RH2.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH27",
      label: "RH27",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.7,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 152\u00d762\u00d716 mm \u00b7 \u00a30.7 ex VAT. Photo: /2d-masters/railheads/photos/RH27.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH32",
      label: "RH32",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.55,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 136\u00d760\u00d714 mm \u00b7 \u00a30.55 ex VAT. Photo: /2d-masters/railheads/photos/RH32.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH36",
      label: "RH36",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.8,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 150\u00d744\u00d733 mm \u00b7 \u00a30.8 ex VAT. Photo: /2d-masters/railheads/photos/RH36.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH37",
      label: "RH37",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.5,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 120\u00d735\u00d730 mm \u00b7 \u00a30.5 ex VAT. Photo: /2d-masters/railheads/photos/RH37.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH38",
      label: "RH38",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.75,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 165\u00d760\u00d724 mm \u00b7 \u00a30.75 ex VAT. Photo: /2d-masters/railheads/photos/RH38.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH39",
      label: "RH39",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 1,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 185\u00d770\u00d727 mm \u00b7 \u00a31.0 ex VAT. Photo: /2d-masters/railheads/photos/RH39.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH3S",
      label: "RH3S",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.2,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 113\u00d755\u00d712 mm \u00b7 \u00a30.2 ex VAT. Photo: /2d-masters/railheads/photos/RH3S.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH41",
      label: "RH41",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.75,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 120\u00d760\u00d725 mm \u00b7 \u00a30.75 ex VAT. Photo: /2d-masters/railheads/photos/RH41.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH42",
      label: "RH42",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 1.75,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 158\u00d793\u00d730 mm \u00b7 \u00a31.75 ex VAT. Photo: /2d-masters/railheads/photos/RH42.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH43",
      label: "RH43",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 3.5,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 200\u00d7118\u00d740 mm \u00b7 \u00a33.5 ex VAT. Photo: /2d-masters/railheads/photos/RH43.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH45",
      label: "RH45",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 134\u00d740\u00d725 mm \u00b7 price TBD. Photo: /2d-masters/railheads/photos/RH45.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH47",
      label: "RH47",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 1.2,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 162\u00d790\u00d716 mm \u00b7 \u00a31.2 ex VAT. Photo: /2d-masters/railheads/photos/RH47.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH51",
      label: "RH51",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.6,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 145\u00d748\u00d726 mm \u00b7 \u00a30.6 ex VAT. Photo: /2d-masters/railheads/photos/RH51.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH52",
      label: "RH52",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.5,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 110\u00d755\u00d726 mm \u00b7 \u00a30.5 ex VAT. Photo: /2d-masters/railheads/photos/RH52.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH55",
      label: "RH55",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 133\u00d772\u00d720 mm \u00b7 price TBD. Photo: /2d-masters/railheads/photos/RH55.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH56",
      label: "RH56",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 125\u00d759\u00d730 mm \u00b7 price TBD. Photo: /2d-masters/railheads/photos/RH56.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH59",
      label: "RH59",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.5,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 194\u00d7108\u00d730 mm \u00b7 \u00a30.5 ex VAT. Photo: /2d-masters/railheads/photos/RH59.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH6",
      label: "RH6",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.7,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 153\u00d724\u00d724 mm \u00b7 \u00a30.7 ex VAT. Photo: /2d-masters/railheads/photos/RH6.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH62",
      label: "RH62",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 60\u00d733\u00d724 mm \u00b7 price TBD. Photo: /2d-masters/railheads/photos/RH62.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH64",
      label: "RH64",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.35,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 140\u00d760\u00d714 mm \u00b7 \u00a30.35 ex VAT. Photo: /2d-masters/railheads/photos/RH64.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH6A",
      label: "RH6A",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 1.4,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 146\u00d740\u00d740 mm \u00b7 \u00a31.4 ex VAT. Photo: /2d-masters/railheads/photos/RH6A.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH6WB",
      label: "RH6WB",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.4,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 100\u00d720\u00d720 mm \u00b7 \u00a30.4 ex VAT \u00b7 with ball. Photo: /2d-masters/railheads/photos/RH6WB.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH7",
      label: "RH7",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.35,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 125\u00d760\u00d712 mm \u00b7 \u00a30.35 ex VAT. Photo: /2d-masters/railheads/photos/RH7.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH70",
      label: "RH70",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 180\u00d752\u00d720 mm \u00b7 price TBD. Photo: /2d-masters/railheads/photos/RH70.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH71",
      label: "RH71",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.7,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 146\u00d767\u00d716 mm \u00b7 \u00a30.7 ex VAT. Photo: /2d-masters/railheads/photos/RH71.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH73",
      label: "RH73",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.65,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 138\u00d760\u00d712 mm \u00b7 \u00a30.65 ex VAT. Photo: /2d-masters/railheads/photos/RH73.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH75",
      label: "RH75",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.8,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 110\u00d748\u00d718 mm \u00b7 \u00a30.8 ex VAT. Photo: /2d-masters/railheads/photos/RH75.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH79",
      label: "RH79",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 153\u00d770\u00d716 mm \u00b7 price TBD. Photo: /2d-masters/railheads/photos/RH79.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH7NP",
      label: "RH7NP",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 0.29,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 110\u00d760\u00d720 mm \u00b7 \u00a30.29 ex VAT \u00b7 no peg. Photo: /2d-masters/railheads/photos/RH7NP.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH81",
      label: "RH81",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 3.25,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 210\u00d7110\u00d725 mm \u00b7 \u00a33.25 ex VAT. Photo: /2d-masters/railheads/photos/RH81.webp",
      adminSlug: "railheads-top",
    },
    {
      slug: "RH9",
      label: "RH9",
      status: 'provisional',
      optionKey: "top_railheads",
      unitPriceGbp: 1.1,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Client catalog: 187\u00d787\u00d716 mm \u00b7 \u00a31.1 ex VAT. Photo: /2d-masters/railheads/photos/RH9.webp",
      adminSlug: "railheads-top",
    },
    // Dog-bar row aliases for primary heads until dedicated SKUs confirmed.
    {
      slug: "RH100-dog",
      label: "RH100 on dog bars",
      status: 'provisional',
      optionKey: "dog_bar_railheads",
      unitPriceGbp: 0.6,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Same unit as RH100 top \u2014 dog-bar row until Marius splits SKUs.",
      adminSlug: "railheads-dog-bars",
    },
    {
      slug: "RH14-dog",
      label: "RH14 on dog bars",
      status: 'provisional',
      optionKey: "dog_bar_railheads",
      unitPriceGbp: 0.5,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Same unit as RH14 top \u2014 dog-bar row until Marius splits SKUs.",
      adminSlug: "railheads-dog-bars",
    },
    {
      slug: "RH32-dog",
      label: "RH32 on dog bars",
      status: 'provisional',
      optionKey: "dog_bar_railheads",
      unitPriceGbp: 0.55,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Same unit as RH32 top \u2014 dog-bar row until Marius splits SKUs.",
      adminSlug: "railheads-dog-bars",
    },
    {
      slug: "RH6WB-dog",
      label: "RH6WB on dog bars",
      status: 'provisional',
      optionKey: "dog_bar_railheads",
      unitPriceGbp: 0.4,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Same unit as RH6WB top \u2014 dog-bar row until Marius splits SKUs.",
      adminSlug: "railheads-dog-bars",
    },
    {
      slug: "RH7-dog",
      label: "RH7 on dog bars",
      status: 'provisional',
      optionKey: "dog_bar_railheads",
      unitPriceGbp: 0.35,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Same unit as RH7 top \u2014 dog-bar row until Marius splits SKUs.",
      adminSlug: "railheads-dog-bars",
    },
    {
      slug: "RH7NP-dog",
      label: "RH7NP on dog bars",
      status: 'provisional',
      optionKey: "dog_bar_railheads",
      unitPriceGbp: 0.29,
      appliesTo: {
        styles: ['traditional_victorian'],
      },
      notes: "Same unit as RH7NP top \u2014 dog-bar row until Marius splits SKUs.",
      adminSlug: "railheads-dog-bars",
    },
  ],
}

